config/routes.rb
# Rails.application.routes.draw do
#   get 'search/search'

#   get 'persons/profile'

#
#   devise_for :users, :controllers => {
#       omniauth_callbacks: 'omniauth_callbacks',
#       sessions: 'custom_session'
#   }
#   # get 'home/index'
#
#   # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#   root 'home#index'
#   # get 'persons/profile', as: 'user_root'
#
# end

Rails.application.routes.draw do

  # We need to define devise_for just omniauth_callbacks:uth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => {
      omniauth_callbacks: 'omniauth_callbacks',
  }
  scope '(:locale)'  do
    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    devise_for :users, skip: [:omniauth_callbacks], controllers: {
        # passwords: 'passwords',
        # registrations: 'registrations',
        sessions: 'custom_session'
    }
    get 'persons/profile', as: 'user_root'
    match 'persons/edit', via: :all
    get 'persons/index'
    get 'persons/show/:id', to: 'persons#show', as: 'persons_show'
    delete 'persons/destroy/:id', to: 'persons#destroy', as: 'persons_destroy'
    post 'persons/block/:id', to: 'persons#block', as: 'persons_block'
    post 'persons/unblock/:id', to: 'persons#unblock', as: 'persons_unblock'
    get 'persons/sort_up_down/:id', to: 'persons#sort_up_down', as: 'persons_sort_up_down'
    get 'persons/sort_down_up/:id', to: 'persons#sort_down_up', as: 'persons_sort_down_up'

    get 'persons/change_theme/(:theme_name)', to: 'persons#change_theme'

    resources :instructions do
      resources :steps do
        resources :blocks
      end
    end


    resources :tags
    get 'search/search'
    root 'home#index'
  end
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one :count_link, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings , :source => :tag
  has_many :steps, :dependent => :destroy

  searchable do
    text :name
    text :user_name do
      user.name
    end
    text :category_name do
      category.name
    end
    text :steps do
      steps.map { |step| step.name }
    end
  end

  PERPAGE = 7
  self.per_page = PERPAGE

  def all_tags=(names)
    created_tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_initialize
    end
    self.tags = created_tags
  end

  def all_tags
    self.tags.map(&:name).join(', ')
  end
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  def create
    authorize! :create, Instruction

    params = instruction_params
    params[:category] = Category.find_by(id: params[:category].to_i)
    @instruction = Instruction.new(params)
    @instruction.user_id = current_user[:id]
    if @instruction.save
      @count_links = CountLink.create(count: 0, instruction_id: @instruction.id)
      flash[:success] = t('user_form.was_update')
      render :show
    else
      render :new
    end
  end

  def show
    authorize! :show, Instruction

    @instruction = Instruction.find(params[:id])
    @count_link = CountLink.find_by(instruction_id: @instruction.id)
    @count_link.count += 1
    @count_link.save
  end


  def edit
    authorize! :update, Instruction
    @instruction = Instruction.find(params[:id])
  end

  def new
    authorize! :create, Instruction
    @instruction = Instruction.new
  end

  def update
    authorize! :update, Instruction

    @instruction = Instruction.find(params[:id])
    params = instruction_params
    params[:category] = Category.find_by(id: params[:category].to_i)
    @instruction.user_id = current_user[:id]
    if @instruction.update_attributes(params)
      redirect_to @instruction
    else
      render :edit
    end
  end

  def destroy
    @instruction = Instruction.find(params[:id])
    authorize! :destroy, @instruction
    @instruction.destroy
    redirect_to user_root_path
  end

  def index
    authorize! :index, Instruction
    @instructions = Instruction.paginate(:page => params[:page], :per_page => 10)
  end

  private

  def instruction_params
    params.require(:instruction).permit(:name, :category, :all_tags)
  end

 end

app/helpers/instructions_helper.rb
module InstructionsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end

end

app/views/instructions/_form.html.erb
<div class="row main">
  <div class="col-md-offset-4 col-md-4">
    <div class="well">
      <%= form_for @instruction do |f| %>

          <div class="form-group">
            <%= f.label t('instructions.name'), class: 'cols-sm-2 control-label' %>
            <div class="cols-sm-10">
              <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: t('instructions.name') %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label t('instructions.category'), class: 'cols-sm-2 control-label' %>
            <div class="cols-sm-10">
              <%= f.select :category, options_for_select(Category.all.map{|s|[s.name, s.id]}), {}, {class: 'form-control select_color'} %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label t('instructions.tags'), class: 'cols-sm-2 control-label' %>
            <div class="cols-sm-10">
              <%= f.text_field :all_tags, autofocus: true, class: 'form-control', placeholder: t('instructions.tags') %>
            </div>
          </div>

          <div class="form-group ">
            <%= f.submit t('instructions.add'), class:'btn btn-primary btn-lg btn-block login-button' %>
          </div>

      <% end %>
    </div>
  </div>
</div>

app/views/instructions/_instruction.html.erb
<h2><%= link_to instruction.name, instruction_path(instruction) %></h2>

app/views/instructions/edit.html.erb
<H1 class="text-center"><%=t('action.change')+' '+ t('instructions.instruction')%></H1>
<%= render 'form' %>

app/views/instructions/index.html.erb
<H1><%= t('action.all_istructions')%></H1>

<div class="panel panel-default">
  <div class="panel-heading"><%= t('instructions.titles') %></div>
  <table border="1" class="table table-striped table-bordered table-hover">
    <tr>
      <th><%=t('instructions.name')%></th>
      <th><%= t('user')%></th>
      <th><%= t('time_update')%></th>
      <th><%= t('instructions.tags')%></th>
    </tr>

    <% @instructions.each do |instruction| %>
        <tr>
          <td><%= link_to instruction.name, instruction_path(instruction.id) %>
          <td><%= instruction.user.name %></td>
          <td><%= instruction.updated_at.localtime.strftime '%d-%m-%Y %H:%M:%S' %></td>
          <td><%= raw instruction.tags.map{ |t| link_to t.name, tag_path(t.name), class: 'tag tag-primary'}.join(" ") %> </td>
        </tr>
    <% end %>
  </table>
</div>

<%= will_paginate @instructions %>

app/views/instructions/new.html.erb
<h1 class="text-center"><%=t('instructions.create')+ ' ' + t('instructions.instruction')%></h1>
<%= render 'form' %>

app/views/instructions/show.html.erb
<h1> <%= @instruction.name %></h1>
<%= link_to t('instructions.add')+ ' ' + t('instructions.step'), new_instruction_step_path(instruction_id: @instruction) %>

<div class="panel panel-default">
  <div class="panel-heading"><%= t('instructions.step') %></div>

  <table border="1" class="table table-striped table-bordered table-hover">
    <tr>
      <th><%=t('instructions.name')%></th>
      <th><%= t('action.change')%></th>
      <th><%= t('action.delete')%></th>
    </tr>

    <% (paginator = @instruction.steps.paginate(page: params[:page])).each do |step| %>
        <tr>
          <td>
            <%= link_to step.name, instruction_step_path(@instruction.id, step.id) %>
            /
            <%= step.blocks.count %>
          </td>
          <% if can? :update, step %>
              <td><%= link_to t('action.change'), edit_instruction_step_path(@instruction.id, step.id) %></td>
          <% end %>
          <% if can? :destroy, step %>
              <td><%= link_to t('action.delete'), instruction_step_path(@instruction.id, step.id), method: :delete, data: {confirm: t('action.warring') } %></td>
          <% end %>
        </tr>
    <% end %>
  </table>
</div>
<%= will_paginate paginator %>