config/routes.rb
# Rails.application.routes.draw do
#   get 'search/search'

#   get 'persons/profile'

#
#   devise_for :users, :controllers => {
#       omniauth_callbacks: 'omniauth_callbacks',
#       sessions: 'custom_session'
#   }
#   # get 'home/index'
#
#   # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#   root 'home#index'
#   # get 'persons/profile', as: 'user_root'
#
# end

Rails.application.routes.draw do

  # We need to define devise_for just omniauth_callbacks:uth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => {
      omniauth_callbacks: 'omniauth_callbacks',
  }
  scope '(:locale)'  do
    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    devise_for :users, skip: [:omniauth_callbacks], controllers: {
        # passwords: 'passwords',
        # registrations: 'registrations',
        sessions: 'custom_session'
    }
    get 'persons/profile', as: 'user_root'
    match 'persons/edit', via: :all
    get 'persons/index'
    get 'persons/show/:id', to: 'persons#show', as: 'persons_show'
    delete 'persons/destroy/:id', to: 'persons#destroy', as: 'persons_destroy'
    post 'persons/block/:id', to: 'persons#block', as: 'persons_block'
    post 'persons/unblock/:id', to: 'persons#unblock', as: 'persons_unblock'
    get 'persons/sort_up_down/:id', to: 'persons#sort_up_down', as: 'persons_sort_up_down'
    get 'persons/sort_down_up/:id', to: 'persons#sort_down_up', as: 'persons_sort_down_up'

    get 'persons/change_theme/(:theme_name)', to: 'persons#change_theme'

    resources :instructions do
      resources :steps do
        resources :blocks
      end
    end


    resources :tags
    get 'search/search'
    root 'home#index'
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController

  def index
    @users = User.all
    authorize! :index, User
  end

  def profile
    authorize! :show_profile, User
    @user_obj = User.find(current_user[:id])
    @user_instructions = Instruction.where(user_id: @user_obj)
  end

  def show
    authorize! :show, Instruction
    @user_obj = User.find(params[:id])
    @user_instructions = Instruction.where(user_id: @user_obj)
  end

  def edit
    authorize! :update, User
    case request.method_symbol
      when :get
        @user = User.find_by(id: current_user[:id])
      when :post
        @user = User.find_by(id: current_user[:id])
        upload_img
        if @user.update_attributes(user_params)
          flash[:success] = t('user_form.was_update')
          redirect_to user_root_path
        else
          redirect_to :back
        end
    end
  end

  def block
    authorize! :block, User
    @user = User.find(params[:id])
    unless @user.banned?
      @user.banned=true
      redirect_to  request.referer if @user.save
    end
  end

  def unblock
    authorize! :block, User
    @user = User.find(params[:id])
    if @user.banned?
      @user.banned=false
      redirect_to  request.referer if @user.save
    end
  end

  def destroy
    authorize! :destroy, User
    @user = User.find(params[:id])
    redirect_to  request.referer if @user.destroy
  end

  def sort_up_down
    @user_obj = User.find(params[:id])
    @user_instructions = Instruction.where(user_id: @user_obj.id).order(:name=>'asc')
  end

  def sort_down_up
    @user_obj = User.find(params[:id])
    @user_instructions = Instruction.where(user_id: @user_obj.id).order(:name=>'desc')
  end

  def change_theme
    begin
      authorize! :change_theme, User
      @user = User.find_by(id: current_user[:id])
      @user.update_attribute(:theme, params[:theme_name])
    rescue AccessGranted::AccessDenied
      flash[:info] = t('settings_menu.non-user')
    end
    redirect_to request.referer
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :lastname, :hobbies, :about)
  end

  def upload_img_param
    params.require(:user).permit(:image)
  end

  def upload_img
    if params[:user].key?("image")
      cloudinary_params = Cloudinary::Uploader.upload(upload_img_param[:image])
      @user.update_attributes(:image => cloudinary_params["url"])
    end
  end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/persons/_form.erb
<div class="col-md-4">
  <ul class="list-group">
    <li class="list-group-item"><%= link_to t('profile'), persons_edit_path %></li>
    <li class="list-group-item"><%= link_to t('users.update_settings'), edit_user_registration_path %></li>
    <li class="list-group-item"><%= link_to t('instructions.create') + ' ' + t('instructions.instruction'), new_instruction_path %></li>
    <li class="list-group-item">
      <%= link_to t('action.all_istructions'), instructions_path %>
      <span class="badge"><%= Instruction.all.count %></span>
    </li>
    <% if can? :index, User %>
        <li class="list-group-item">
          <%= link_to t('users.all_users'), persons_index_path %>
          <span class="badge"><%= User.all.count %></span>
        </li>
    <% end %>
  </ul>

</div>

<style>
  .word-wrap-panel {
    word-wrap: break-word;
  }
</style>

<div class="col-md-8">
  <div class="row">
    <div class="well well-sm">
      <h4 class="text-center"><%=@user_obj.email%></h4>
    </div>
  </div>
  <div class="row">

    <div class="col-md-5">
      <img src="<%=@user_obj.image %>" alt=<%=t('user_form.image') %> width="300" height="300" align="left">
    </div>

    <div class="col-md-7">
      <div class="list-group">
        <a href="#" class="list-group-item">
          <h4 class="list-group-item-heading"><%=t('user_form.first_name') %></h4>
          <p class="list-group-item-text word-wrap-panel"><%=@user_obj.firstname %></p>
        </a>
        <a href="#" class="list-group-item">
          <h4 class="list-group-item-heading"><%=t('user_form.last_name') %></h4>
          <p class="list-group-item-text word-wrap-panel"><%=@user_obj.lastname %></p>
        </a>
        <a href="#" class="list-group-item">
          <h4 class="list-group-item-heading"><%=t('user_form.hobbies') %></h4>
          <p class="list-group-item-text word-wrap-panel"><%=@user_obj.hobbies %></p>
        </a>
        <a href="#" class="list-group-item">
          <h4 class="list-group-item-heading"><%=t('user_form.about') %></h4>
          <p class="list-group-item-text word-wrap-panel"><%=@user_obj.about %></p>
        </a>
      </div>


    </div>
  </div>

  <div>
    <p>
      <b align="left"><%=t('action.sort')%></b>
      <%= link_to  raw('<span class="glyphicon glyphicon-sort-by-attributes-alt" aria-hidden="true"></span>'), persons_sort_up_down_path(@user_obj.id)%>
      <%= link_to  raw('<span class="glyphicon glyphicon-sort-by-attributes" aria-hidden="true"></span>'), persons_sort_down_up_path(@user_obj.id)%>
    <p>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading"><%= t('instructions.titles') %></div>

    <table class="table table-striped table-bordered table-hover" id="instructions">
      <thead>
      <tr>
        <th><%=t('instructions.name')%></th>
        <th><%=t('instructions.category')%></th>
        <th><%=t('instructions.tags')%></th>
        <th><%= t('action.change')%></th>
        <th><%= t('action.delete')%></th>
      </tr>
      </thead>
      <tbody>

      <% paginator = @user_instructions.paginate(page: params[:page], per_page: 5)%>

      <%= render 'instruction', {paginator: paginator} %>
      </tbody>


    </table>
    <%= will_paginate paginator %>
  </div>

</div>

app/views/persons/_instruction.html.erb
<% paginator.each do |instruction| %>
    <tr>
      <td>
        <%= link_to instruction.name, instruction_path(instruction)%>
        <% if false %>
            <%= instruction.steps.count %>
            /
            <%= instruction.steps.map{|s| s.blocks.count }.sum %>
        <%end%>
      </td>
      <td><%= instruction.category.name %> </td>
      <td><%= raw instruction.tags.map{ |t| link_to t.name, tag_path(t.name), class: 'tag tag-primary'}.join(" ") %> </td>
      <% if can? :update, instruction %>
          <td><%= link_to t('action.change'), edit_instruction_path(instruction)%></td>
      <%	 end %>
      <% if can? :destroy, instruction %>
          <td><%= link_to t('action.delete'), instruction_path(instruction), method: :delete, data: {confirm: t('action.warring') }%></td>
      <%	 end %>
    </tr>
<% end %>

app/views/persons/edit.html.erb
<div class="row main">
  <div class="main-login main-center">
    <%= form_for @user, url: {:controller => "persons", :action => "edit"} do |f| %>

        <div class="form-group">
          <%= f.label t('user_form.first_name'), class: 'cols-sm-2 control-label' %>
          <div class="cols-sm-10">
              <%= f.text_field :firstname, autofocus: true, class: 'form-control', placeholder: t('user_form.first_name') %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label t('user_form.last_name'), class: 'cols-sm-2 control-label' %>
          <div class="cols-sm-10">
              <%= f.text_field :lastname, autofocus: true, class: 'form-control', placeholder: t('user_form.last_name') %>
          </div>
        </div>

            <div class="form-group">
              <%= f.label t('user_form.image'), class: 'cols-sm-2 control-label' %>
              <div class="input-group">
            <span class="input-group-btn">
                <span class="btn btn-primary btn-file">
                 <%=  t('user_form.upload')  %> <%= f.file_field :image, id: 'imgInp' %>
                </span>
            </span>
                <input type="text" class="form-control" readonly>
              </div>
              <img id='img-upload'/>
            </div>

        <div class="form-group">
          <%= f.label t('user_form.hobbies'), class: 'cols-sm-2 control-label' %>
          <div class="cols-sm-10">
              <%= f.text_area :hobbies, autofocus: true, class: 'form-control', placeholder: t('user_form.hobbies') %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label t('user_form.about'), class: 'cols-sm-2 control-label' %>
          <div class="cols-sm-10">
            <%= f.text_area :about, autofocus: true, class: 'form-control', placeholder: t('user_form.about') %>
          </div>
        </div>

        <div class="form-group ">
          <%= f.submit t('user_form.edit'), class:'btn btn-primary btn-lg btn-block login-button' %>
        </div>

  <% end %>
  </div>
</div>

app/views/persons/index.html.erb
<%=t('users.all_users')%>
<table border="1" class="table">
  <tr>
    <th class="avatar_column"><%= t('user_form.image')%></th>
    <th><%=t('user')%></th>
    <th>email</th>
    <th><%=t('users.created_at')%></th>
    <% if can? :block, User %>
        <th><%= t('action.block')%></th>
    <% end %>
    <% if can? :destroy, User %>
        <th><%= t('action.delete')%></th>
    <% end %>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td class="avatar_column"><img src="<%=user.image %>" alt="Avatar" width="70" height="70" border="0"></td>
        <td><%= user.name %> </td>
        <td><%= link_to user.email, persons_show_path(user)%> </td>
        <td><%= user.created_at.localtime.strftime '%d-%m-%Y %H:%M:%S' %></td>
        <% if can? :block, User %>
            <% if user.banned? %>
                <td><%= link_to t('action.unblock'), persons_unblock_path(user), method: :post %></td> <!-- @TODO: user.block -->
            <% else %>
                <td><%= link_to t('action.block'), persons_block_path(user), method: :post %></td> <!-- @TODO: user.block -->
            <% end %>
        <% end %>
        <% if can? :destroy, User %>
            <td><%= link_to t('action.delete'), persons_destroy_path(user), method: :delete, data: {confirm: t('action.warring') }%></td>
      <% end %>
      </tr>
  <% end %>
</table>

app/views/persons/profile.html.erb
<%= render 'form' %>

app/views/persons/profile.js.erb
<% paginator = @user_instructions.paginate(page: params[:page])%>

var appender = "<%= j render('instruction', {paginator: paginator}) %>";

$('#instructions tbody').append(appender);

<% if paginator.next_page %>
$('.pagination').replaceWith("<%= j  will_paginate(paginator) %>");
<% else %>
$('.pagination').remove();
<% end %>

app/views/persons/show.erb
<%=render "form" %>

app/views/persons/show.js.erb
<% paginator = @user_instructions.paginate(page: params[:page])%>

var appender = "<%= j render('instruction', {paginator: paginator}) %>";

$('#instructions tbody').append(appender);

<% if paginator.next_page %>
$('.pagination').replaceWith("<%= j  will_paginate(paginator) %>");
<% else %>
$('.pagination').remove();
<% end %>

app/views/persons/sort_down_up.html.erb
<%=render "form"%>

app/views/persons/sort_down_up.js.erb
<% paginator = @user_instructions.paginate(page: params[:page])%>

var appender = "<%= j render('instruction', {paginator: paginator}) %>";

$('#instructions tbody').append(appender);

<% if paginator.next_page %>
$('.pagination').replaceWith("<%= j  will_paginate(paginator) %>");
<% else %>
$('.pagination').remove();
<% end %>

app/views/persons/sort_up_down.html.erb
<%=render "form"%>

app/views/persons/sort_up_down.js.erb
<% paginator = @user_instructions.paginate(page: params[:page])%>

var appender = "<%= j render('instruction', {paginator: paginator}) %>";

$('#instructions tbody').append(appender);

<% if paginator.next_page %>
$('.pagination').replaceWith("<%= j  will_paginate(paginator) %>");
<% else %>
$('.pagination').remove();
<% end %>