config/routes.rb
# Rails.application.routes.draw do
#   get 'search/search'

#   get 'persons/profile'

#
#   devise_for :users, :controllers => {
#       omniauth_callbacks: 'omniauth_callbacks',
#       sessions: 'custom_session'
#   }
#   # get 'home/index'
#
#   # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#   root 'home#index'
#   # get 'persons/profile', as: 'user_root'
#
# end

Rails.application.routes.draw do

  # We need to define devise_for just omniauth_callbacks:uth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:session, :password, :registration, :confirmation], :controllers => {
      omniauth_callbacks: 'omniauth_callbacks',
  }
  scope '(:locale)'  do
    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    devise_for :users, skip: [:omniauth_callbacks], controllers: {
        # passwords: 'passwords',
        # registrations: 'registrations',
        sessions: 'custom_session'
    }
    get 'persons/profile', as: 'user_root'
    match 'persons/edit', via: :all
    get 'persons/index'
    get 'persons/show/:id', to: 'persons#show', as: 'persons_show'
    delete 'persons/destroy/:id', to: 'persons#destroy', as: 'persons_destroy'
    post 'persons/block/:id', to: 'persons#block', as: 'persons_block'
    post 'persons/unblock/:id', to: 'persons#unblock', as: 'persons_unblock'
    get 'persons/sort_up_down/:id', to: 'persons#sort_up_down', as: 'persons_sort_up_down'
    get 'persons/sort_down_up/:id', to: 'persons#sort_down_up', as: 'persons_sort_down_up'

    get 'persons/change_theme/(:theme_name)', to: 'persons#change_theme'

    resources :instructions do
      resources :steps do
        resources :blocks
      end
    end


    resources :tags
    get 'search/search'
    root 'home#index'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaintSite</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag :application %>
  <%= stylesheet_link_tag :tags %>

  <%= stylesheet_link_tag "themes/#{current_user_theme}_bootstrap" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <%= link_to raw('<img alt="Sova" src="http://res.cloudinary.com/dpoas7y00/image/upload/c_scale,w_20/v1501857180/Actions-go-home_tcqgu4.ico">'), root_path , class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">

        <% if user_signed_in? %>
            <li>
              <%= link_to t('profile'), user_root_path, {'data-toggle': 'tooltip', 'data-placement': 'bottom', title: t('profile_tooltip')} %>
            </li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" <% if user_signed_in? %> style="color: rgb(0,133,185);"<% end %> >
            <%= t('autorithation_menu.sign_in') %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
                <li><%= link_to t('autorithation_menu.sign_out'), destroy_user_session_path, :method => :delete %></li>
            <% else %>
                <li class="dropdown-submenu">
                  <a href="#"><%= t('autorithation_menu.sign_in') %></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to t('autorithation_menu.sign_in_with')+' email', new_user_session_path %></li>
                    <li><%= link_to t('autorithation_menu.sign_in_with')+' Facebook', localized_omniauth_path(:facebook) %></li>
                    <li><%= link_to t('autorithation_menu.sign_in_with')+' vk', localized_omniauth_path(:vkontakte) %></li>
                    <li><%= link_to t('autorithation_menu.sign_in_with')+' twitter', localized_omniauth_path(:twitter) %></li>
                    <li><%= link_to t('autorithation_menu.sign_in_with')+' Google', localized_omniauth_path(:google_oauth2) %></li>
                  </ul>
                </li>

                <li><%= link_to t('autorithation_menu.sign_up'), new_user_registration_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= t('settings') %>
            <span class="caret"></span>
          </a>

          <ul class="dropdown-menu">
            <li class="dropdown-submenu">
              <a href="#"><%= t('settings_menu.themes') %></a>
              <ul class="dropdown-menu">
                <% available_themes.each do |theme_name| %>
                    <li><%= link_to theme_name.capitalize,  controller: '/persons', action: 'change_theme', theme_name: theme_name %></li>
                <% end %>
              </ul>
            </li>

            <li class="dropdown-submenu">
              <a href="#"><%= t('settings_menu.languages') %></a>
              <ul class="dropdown-menu">
                <li><%= link_to t('settings_menu.languages_m.en'), {locale: :en} %></li>
                <li><%= link_to t('settings_menu.languages_m.ru'), {locale: :ru} %></li>
              </ul>
            </li>

          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-left">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= t('action_menu.actions') %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li class="dropdown-submenu">
              <a href="#"><%= t('action_menu.view') %></a>
              <ul class="dropdown-menu">
                <li><%= link_to t('users.all_users'),  controller: '/persons', action: 'index'  %></li>
                <li><%= link_to t('action.all_istructions'), instructions_path %></li>
              </ul>
            </li>

          </ul>
        </li>
      </ul>

      <form action="<%= search_search_path %>" class="navbar-form navbar-left" method="get">
        <div class="form-group">
          <input name="search" type="text" class="form-control" placeholder=<%=t('action.search_place')%>>
        </div>
        <button type="submit" class="btn btn-default"><%= t('action.go') %></button>
      </form>

      <div class="navbar-right">
        <% if current_user != nil %>
            <p class="navbar-text"><%= current_user.role %></p>
        <% end %>
      </div>

    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="tag_cloud well">
        <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
            <%= link_to tag.name, tag_path(tag.name), class: css_class %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
        <%= puts key %>
        <%= puts value %>
    <% end %>
  </div>
  <div class="row">
    <%= yield %>
  </div>
</div>

</body>
</html>